
INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('재호햄이 계속 리플렉션 훔쳐본다아','심심한 것 같다','도은햄');

INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('오늘 야구공빵 먹을 것','무조건','재호햄');

INSERT INTO BOARD(TITLE, CONTENTS, WRITER)
VALUES('핫도그도 먹을 것','무조건','재호햄');

COMMIT;

SELECT*FROM BOARD;